### ISSUE TITLE
"es" (spanish) translations are not working properly.

### ISSUE THREAD

**Issue by henrich-mauritz** [crowdin/mobile-sdk-ios#223]
with configuration:

`CrowdinSDK.currentLocalization = "es"`
`let config = CrowdinSDKConfig.config().with(crowdinProviderConfig: providerConfig).with(intervalUpdatesEnabled: true, interval: 15*60)`
`_ = CrowdinSDK.addDownloadHandler { print("\(Date()) Crowdin: strings downloaded")  }`

I'm never getting any callback from that handler. I tried waiting 15 mins, reinstalling app. Simply not happening.
When I changed it to different language in Crowdin eg. "es-EM" (modern spanish) or "sl" (slovenian), it works just fine.

My Android college reports the same problem. Is there something I'm missing ?

**Comment by serejaonly** [comment]
We had the same problem when we switched to Crowdin Enterprise and the first request for all languages gave us wrong list because it went to basic Crowdin, not enterprise.

To fix that you need to pass parameter `organizationName` in `CrowdinAPI` but now there's no possibility to do that. You can pass it with login config but it's basically needed for real-time preview feature and doesn't change it in `CrowdinAPI`.
So we had to fork the repo and add `organizationName` parameter directly in `CrowdinAPI`. That works!

I think it should be configurable with `CrowdinProviderConfig` because you don't need the whole login config if you just switched to enterprise.

**Comment by andrii-bodnar** [comment]
Recently we released the [new version](https://github.com/crowdin/mobile-sdk-android/releases/tag/1.8.0) of the Android SDK with the fix for such a situation.

The same thing should be applied here. We should move the `organizationName` to the `CrowdinProviderConfig` level keeping the backward compatibility.
